use crate::sys;

simple_enum! {
    /// Valid values for priority of Thread.
    pub enum ThreadPriority(sys::FlutterThreadPriority) {
        /// Suitable for threads that shouldn't disrupt high priority work.
        Background,
        /// Default priority level.
        Normal,
        /// Suitable for threads which generate data for the display.
        Display,
        /// Suitable for thread which raster data.
        Raster,
    }
}

/// Unique identifier for views.
///
/// View IDs are generated by the embedder and are
/// opaque to the engine; the engine does not interpret view IDs in any way.
///
/// EXCEPT for the implicit view, which has a view ID of 0. You cannot add another view with ID of 0, nor can you remove the implicit view.
#[repr(transparent)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub struct ViewId(pub sys::FlutterViewId);

impl ViewId {
    /// The implicit view ID. It has an ID of 0 and always exists. It cannot be removed.
    pub const IMPLICIT: Self = Self(0);
}
